/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg06royalpavyon;

import javax.swing.JLabel;

/**
 *
 * @author armagan
 */
public class bjFrame extends javax.swing.JFrame {

    /**
     * Creates new form bjFrame
     */
    gamesFrame games;

    public bjFrame(gamesFrame game) {
        games = game;
        initComponents();
        gizliPass.setVisible(false);
        kLabel.setVisible(false);
        yLabel.setVisible(false);
        kasaLabel.setVisible(false);
        youLabel.setVisible(false);
        btnHit.setVisible(false);
        btnStand.setVisible(false);
        wonLostLabel.setVisible(false);
        kasaTotalCard.setVisible(false);
    }

    public JLabel getSolBankLabel() {
        return solBankLabel;
    }

    public void setSolBankLabel(JLabel solBankLabel) {
        this.solBankLabel = solBankLabel;
    }

    public JLabel getSolUserLabel() {
        return solUserLabel;
    }

    public void setSolUserLabel(JLabel solUserLabel) {
        this.solUserLabel = solUserLabel;
    }

    public JLabel getGizliPass() {
        return gizliPass;
    }

    public void setGizliPass(JLabel gizliPass) {
        this.gizliPass = gizliPass;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        betTF = new javax.swing.JTextField();
        btnBet = new javax.swing.JButton();
        kLabel = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        kasaLabel = new javax.swing.JLabel();
        youLabel = new javax.swing.JLabel();
        btnHit = new javax.swing.JButton();
        btnStand = new javax.swing.JButton();
        wonLostLabel = new javax.swing.JLabel();
        solUserLabel = new javax.swing.JLabel();
        solBankLabel = new javax.swing.JLabel();
        kasaTotalCard = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        gizliPass = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        arka = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        betTF.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        betTF.setText("100");
        betTF.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 3, 18))); // NOI18N
        jPanel1.add(betTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 166, 93, -1));

        btnBet.setText("BET");
        btnBet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBetActionPerformed(evt);
            }
        });
        jPanel1.add(btnBet, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 162, 90, 40));

        kLabel.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        kLabel.setForeground(new java.awt.Color(255, 255, 255));
        kLabel.setText("Kasa: ");
        jPanel1.add(kLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, -1, -1));

        yLabel.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        yLabel.setForeground(new java.awt.Color(255, 255, 255));
        yLabel.setText("You:");
        jPanel1.add(yLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        kasaLabel.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        kasaLabel.setForeground(new java.awt.Color(255, 255, 255));
        kasaLabel.setText("jLabel5");
        jPanel1.add(kasaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, -1, -1));

        youLabel.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        youLabel.setForeground(new java.awt.Color(255, 255, 255));
        youLabel.setText("jLabel6");
        jPanel1.add(youLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));

        btnHit.setText("HIT");
        btnHit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitActionPerformed(evt);
            }
        });
        jPanel1.add(btnHit, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 74, -1));

        btnStand.setText("STAND");
        btnStand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStandActionPerformed(evt);
            }
        });
        jPanel1.add(btnStand, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, -1, -1));

        wonLostLabel.setFont(new java.awt.Font("Kozuka Gothic Pro M", 1, 18)); // NOI18N
        wonLostLabel.setForeground(new java.awt.Color(255, 255, 255));
        wonLostLabel.setText("jLabel5");
        jPanel1.add(wonLostLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        solUserLabel.setBackground(new java.awt.Color(255, 255, 255));
        solUserLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        solUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        solUserLabel.setText("jLabel3");
        jPanel1.add(solUserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        solBankLabel.setBackground(new java.awt.Color(0, 0, 0));
        solBankLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        solBankLabel.setForeground(new java.awt.Color(255, 255, 255));
        solBankLabel.setText("jLabel4");
        jPanel1.add(solBankLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        kasaTotalCard.setText("jLabel3");
        jPanel1.add(kasaTotalCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 105, -1, -1));

        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        jPanel1.add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 395, -1, -1));

        gizliPass.setText("jLabel3");
        jPanel1.add(gizliPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 21, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg06royalpavyon/bjTable3.png"))); // NOI18N
        jLabel3.setText("background");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 450, 460));

        arka.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg06royalpavyon/arka.png"))); // NOI18N
        jPanel1.add(arka, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBetActionPerformed
        double bet = Double.parseDouble(betTF.getText());
        int kasaC1 = CasinoSys.startKasa();
        int kasa = CasinoSys.startKasa2(kasaC1);
        int user = CasinoSys.startUser();
        kasaTotalCard.setText("" + kasa);

        kasaLabel.setText(kasaC1 + " + CARD");
        youLabel.setText("" + user);
        btnHit.setVisible(true);
        btnStand.setVisible(true);
        kLabel.setVisible(true);
        yLabel.setVisible(true);
        kasaLabel.setVisible(true);
        youLabel.setVisible(true);
        // kasatoplam.setText("" + kasa);
        // userToplam.setText("" + user);
        wonLostLabel.setText("");
        wonLostLabel.setVisible(true);
    }//GEN-LAST:event_btnBetActionPerformed

    private void btnHitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitActionPerformed
        int user = Integer.parseInt(youLabel.getText());
        int newcard = CasinoSys.giveCard(user);
        user += newcard;

        youLabel.setText("" + user);

        if (user > 21) {
            btnHit.setVisible(false);
            btnStand.setVisible(false);
            wonLostLabel.setText("You Lost.");
            double bank = Double.parseDouble(solBankLabel.getText());
            double bet2 = Double.parseDouble(betTF.getText());
            double newbank = (bank - bet2);
            solBankLabel.setText("" + newbank);
            btnHit.setVisible(false);
            btnStand.setVisible(false);
        } else if (user == 21) {
            btnHit.setVisible(false);
            btnStand.setVisible(false);
            wonLostLabel.setText("YOU WON.");
            double bank = Double.parseDouble(solBankLabel.getText());
            double bet2 = Double.parseDouble(betTF.getText());
            double newbank = (bank + bet2);
            solBankLabel.setText("" + newbank);
            btnHit.setVisible(false);
            btnStand.setVisible(false);
        }
    }//GEN-LAST:event_btnHitActionPerformed

    private void btnStandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStandActionPerformed
        int kasaToplam = Integer.parseInt(kasaTotalCard.getText());
        int userTplm = Integer.parseInt(youLabel.getText());
        int yeniKasa = CasinoSys.kasaKartCek(kasaToplam);
        int bet = Integer.parseInt(betTF.getText());

        kasaLabel.setText("" + yeniKasa);

        wonLostLabel.setText(CasinoSys.sonuc(userTplm, yeniKasa, bet));
        if (CasinoSys.sonuc(userTplm, yeniKasa, bet) == "YOU WON") {
            double bank = Double.parseDouble(solBankLabel.getText());
            double bet2 = Double.parseDouble(betTF.getText());
            double newbank = bank + bet2;
            kasaLabel.setText("" + yeniKasa);
            solBankLabel.setText("" + newbank);
            btnHit.setVisible(false);
            btnStand.setVisible(false);
        } else if (CasinoSys.sonuc(userTplm, yeniKasa, bet) == "Push.") {
            btnHit.setVisible(false);
            btnStand.setVisible(false);
        } else if (CasinoSys.sonuc(userTplm, yeniKasa, bet) == "You Lost.") {
            double bank = Double.parseDouble(solBankLabel.getText());
            double bet2 = Double.parseDouble(betTF.getText());
            double newbank = bank - bet2;
            kasaLabel.setText("" + yeniKasa);
            solBankLabel.setText("" + newbank);
            btnHit.setVisible(false);
            btnStand.setVisible(false);
        }
    }//GEN-LAST:event_btnStandActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        //Games g = new Games(solUserLabel.getText(), gizliPass.getText(), Double.parseDouble(solBankLabel.getText()));
        for (int i = 0; i < CasinoSys.casinoList.size(); i++) {
            if (solUserLabel.getText().equalsIgnoreCase(CasinoSys.casinoList.get(i).getUsername())) {
                CasinoSys.casinoList.get(i).setBankAccount(Double.parseDouble(solBankLabel.getText()));
            }
        }

        games.setVisible(true);
        this.setVisible(false);
        games.getBankLabel().setText(solBankLabel.getText());
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arka;
    private javax.swing.JTextField betTF;
    private javax.swing.JButton btnBet;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHit;
    private javax.swing.JButton btnStand;
    private javax.swing.JLabel gizliPass;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kLabel;
    private javax.swing.JLabel kasaLabel;
    private javax.swing.JLabel kasaTotalCard;
    private javax.swing.JLabel solBankLabel;
    private javax.swing.JLabel solUserLabel;
    private javax.swing.JLabel wonLostLabel;
    private javax.swing.JLabel yLabel;
    private javax.swing.JLabel youLabel;
    // End of variables declaration//GEN-END:variables
}
