/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg06royalpavyon;

import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author berk
 */
public class diceFrame extends javax.swing.JFrame {

    /**
     * Creates new form diceFrame
     */
    gamesFrame games;

    public diceFrame(gamesFrame game) {
        games = game;
        initComponents();
        gizliPass.setVisible(false);
        kasa.setVisible(false);
        you.setVisible(false);
        kasaZar.setVisible(false);
        userZar.setVisible(false);
        wonLostLabel.setVisible(false);

    }

    public JLabel getGizliPass() {
        return gizliPass;
    }

    public JLabel getSolBankLabel() {
        return solBankLabel;
    }

    public JLabel getSolUserLabel() {
        return solUserLabel;
    }

    public void setGizliPass(JLabel gizliPass) {
        this.gizliPass = gizliPass;
    }

    public void setSolBankLabel(JLabel solBankLabel) {
        this.solBankLabel = solBankLabel;
    }

    public void setSolUserLabel(JLabel solUserLabel) {
        this.solUserLabel = solUserLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        solBankLabel = new javax.swing.JLabel();
        solUserLabel = new javax.swing.JLabel();
        gizliPass = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        btnBet = new javax.swing.JButton();
        tfBet = new javax.swing.JTextField();
        kasa = new javax.swing.JLabel();
        you = new javax.swing.JLabel();
        kasaZar = new javax.swing.JLabel();
        userZar = new javax.swing.JLabel();
        wonLostLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        solBankLabel.setBackground(new java.awt.Color(255, 255, 255));
        solBankLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        solBankLabel.setForeground(new java.awt.Color(255, 255, 255));
        solBankLabel.setText("jLabel4");
        getContentPane().add(solBankLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 57, -1, -1));

        solUserLabel.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        solUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        solUserLabel.setText("jLabel3");
        getContentPane().add(solUserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 34, -1, -1));

        gizliPass.setText("jLabel3");
        getContentPane().add(gizliPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(163, 22, -1, -1));

        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 520, -1, 30));

        btnBet.setText("BET");
        btnBet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBetActionPerformed(evt);
            }
        });
        getContentPane().add(btnBet, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 80, 40));

        tfBet.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        tfBet.setText("100");
        getContentPane().add(tfBet, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 83, -1));

        kasa.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        kasa.setForeground(new java.awt.Color(255, 255, 255));
        kasa.setText("Kasa:");
        getContentPane().add(kasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, -1, -1));

        you.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        you.setForeground(new java.awt.Color(255, 255, 255));
        you.setText("You:");
        getContentPane().add(you, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 450, -1, -1));

        kasaZar.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        kasaZar.setForeground(new java.awt.Color(255, 255, 255));
        kasaZar.setText("jLabel3");
        getContentPane().add(kasaZar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        userZar.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        userZar.setForeground(new java.awt.Color(255, 255, 255));
        userZar.setText("jLabel4");
        getContentPane().add(userZar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));

        wonLostLabel.setFont(new java.awt.Font("Kozuka Gothic Pro H", 1, 18)); // NOI18N
        wonLostLabel.setForeground(new java.awt.Color(255, 255, 255));
        wonLostLabel.setText("jLabel3");
        getContentPane().add(wonLostLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg06royalpavyon/sondice.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        //Games g = new Games(solUserLabel.getText(), gizliPass.getText(), Double.parseDouble(solBankLabel.getText()));
        for (int i = 0; i < CasinoSys.casinoList.size(); i++) {
            if (solUserLabel.getText().equalsIgnoreCase(CasinoSys.casinoList.get(i).getUsername())) {
                CasinoSys.casinoList.get(i).setBankAccount(Double.parseDouble(solBankLabel.getText()));
            }
        }
        

        games.setVisible(true);
        this.setVisible(false);
        games.getBankLabel().setText(solBankLabel.getText());
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnBetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBetActionPerformed
        double bet = Double.parseDouble(tfBet.getText());

        ArrayList<Integer> arr = CasinoSys.playDice();

        kasaZar.setText("" + arr.get(0) + " + " + arr.get(1) + "      TOTAL: " + arr.get(2));
        userZar.setText("" + arr.get(3) + " + " + arr.get(4) + "      TOTAL: " + arr.get(5));

        if (arr.get(2) > arr.get(5)) {
            wonLostLabel.setText("You Lost.");
            double bank = Double.parseDouble(solBankLabel.getText());
            double bet2 = Double.parseDouble(tfBet.getText());
            double newbank = (bank - bet2);
            solBankLabel.setText("" + newbank);
        } else if (arr.get(2) < arr.get(5)) {
            wonLostLabel.setText("YOU WON");
            double bank = Double.parseDouble(solBankLabel.getText());
            double bet2 = Double.parseDouble(tfBet.getText());
            double newbank = (bank + bet2);
            solBankLabel.setText("" + newbank);
        } else {
            wonLostLabel.setText("Push.");
        }
        kasa.setVisible(true);
        you.setVisible(true);
        kasaZar.setVisible(true);
        userZar.setVisible(true);
        wonLostLabel.setVisible(true);
    }//GEN-LAST:event_btnBetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBet;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel gizliPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel kasa;
    private javax.swing.JLabel kasaZar;
    private javax.swing.JLabel solBankLabel;
    private javax.swing.JLabel solUserLabel;
    private javax.swing.JTextField tfBet;
    private javax.swing.JLabel userZar;
    private javax.swing.JLabel wonLostLabel;
    private javax.swing.JLabel you;
    // End of variables declaration//GEN-END:variables
}
