/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg06royalpavyon;

import java.awt.Image;
import static java.awt.Image.SCALE_SMOOTH;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author armagan
 */
public class girisFrame extends javax.swing.JFrame {

    /**
     * Creates new form girisFrame
     */
    gamesFrame game = new gamesFrame(this);
    addFrame add = new addFrame(this);

    public girisFrame() {
        initComponents();
        
        hataLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        usernameTF = new javax.swing.JTextField();
        btnLogin = new javax.swing.JToggleButton();
        hataLabel = new javax.swing.JLabel();
        Signbtn = new javax.swing.JButton();
        passwordTF = new javax.swing.JPasswordField();
        but1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usernameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTFActionPerformed(evt);
            }
        });
        jPanel1.add(usernameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 120, -1));

        btnLogin.setText("LOGIN");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        btnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnLoginKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btnLoginKeyReleased(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, -1, -1));

        hataLabel.setText("jLabel4");
        jPanel1.add(hataLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        Signbtn.setText("SIGN UP");
        Signbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Signbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, -1));

        passwordTF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordTFKeyPressed(evt);
            }
        });
        jPanel1.add(passwordTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 122, -1));

        but1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                but1MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                but1MouseEntered(evt);
            }
        });
        jPanel1.add(but1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 120, 90));

        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 130, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg06royalpavyon/SONGİRİŞ.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       String username = usernameTF.getText();
        String password = passwordTF.getText();
        String name;

        CasinoSys.users();

        for (int i = 0; i < CasinoSys.casinoList.size(); i++) {
            if (username.equalsIgnoreCase(CasinoSys.casinoList.get(i).getUsername())) {
                if (password.equals(CasinoSys.casinoList.get(i).getPassword())) {
                    game.setVisible(true);
                    this.setVisible(false);
                    double bankAccount = CasinoSys.casinoList.get(i).getBankAccount();
                    game.getUsernameLabel().setText(username);
                    game.getGizliPassL().setText(password);
                    game.getBankLabel().setText("" + bankAccount);

                    // Games g = new Games(username, password, bankAccount);
                } else {
                    hataLabel.setText("Wrong Password.");
                    hataLabel.setVisible(true);
                }
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void SignbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignbtnActionPerformed
        add.setVisible(true);
    }//GEN-LAST:event_SignbtnActionPerformed

    private void btnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyPressed

    }//GEN-LAST:event_btnLoginKeyPressed

    private void btnLoginKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnLoginKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginKeyReleased

    private void passwordTFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTFKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        String username = usernameTF.getText();
        String password = passwordTF.getText();
        String name;

        CasinoSys.users();

        for (int i = 0; i < CasinoSys.casinoList.size(); i++) {
            if (username.equalsIgnoreCase(CasinoSys.casinoList.get(i).getUsername())) {
                if (password.equals(CasinoSys.casinoList.get(i).getPassword())) {
                    game.setVisible(true);
                    this.setVisible(false);
                    double bankAccount = CasinoSys.casinoList.get(i).getBankAccount();
                    game.getUsernameLabel().setText(username);
                    game.getGizliPassL().setText(password);
                    game.getBankLabel().setText("" + bankAccount);

                    // Games g = new Games(username, password, bankAccount);
                } else {
                    hataLabel.setText("Wrong Password.");
                    hataLabel.setVisible(true);
                }
            }
        }
        }
    }//GEN-LAST:event_passwordTFKeyPressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void but1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but1MouseEntered
        ImageIcon myimage=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("kafaben.jpg")));
        Image img1=myimage.getImage();
        Image img2=img1.getScaledInstance(but1.getWidth(), but1.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i=new ImageIcon(img2);
        but1.setIcon(i);
    }//GEN-LAST:event_but1MouseEntered

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        ImageIcon myimage=new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("kafaa.jpg")));
        Image img1=myimage.getImage();
        Image img2=img1.getScaledInstance(jButton3.getWidth(), jButton3.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i=new ImageIcon(img2);
        jButton3.setIcon(i);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        jButton3.setIcon(null);
    }//GEN-LAST:event_jButton3MouseExited

    private void but1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but1MouseExited
        but1.setIcon(null);
    }//GEN-LAST:event_but1MouseExited

    private void usernameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTFActionPerformed

    public JTextField getUsernameTF() {
        return usernameTF;
    }

    public void setUsernameTF(JTextField usernameTF) {
        this.usernameTF = usernameTF;
    }

    public JPasswordField getPasswordTF() {
        return passwordTF;
    }

    public void setPasswordTF(JPasswordField passwordTF) {
        this.passwordTF = passwordTF;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(girisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(girisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(girisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(girisFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new girisFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Signbtn;
    private javax.swing.JToggleButton btnLogin;
    private javax.swing.JButton but1;
    private javax.swing.JLabel hataLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
