/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkg06royalpavyon;

import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author berk
 */
public class slotFrame extends javax.swing.JFrame {

    /**
     * Creates new form slotFrame
     */
    gamesFrame games;

    public slotFrame(gamesFrame game) {
        games = game;
        initComponents();
        gizliPass.setVisible(false);

    }

    public JLabel getGizliPass() {
        return gizliPass;
    }

    public void setGizliPass(JLabel gizliPass) {
        this.gizliPass = gizliPass;
    }

    public JLabel getSolBankLabel() {
        return solBankLabel;
    }

    public void setSolBankLabel(JLabel solBankLabel) {
        this.solBankLabel = solBankLabel;
    }

    public JLabel getSolUserLabel() {
        return solUserLabel;
    }

    public void setSolUserLabel(JLabel solUserLabel) {
        this.solUserLabel = solUserLabel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        solBankLabel = new javax.swing.JLabel();
        solUserLabel = new javax.swing.JLabel();
        gizliPass = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        tfBet = new javax.swing.JTextField();
        btnBet = new javax.swing.JButton();
        wonLostLabel = new javax.swing.JLabel();
        field1 = new javax.swing.JTextField();
        field2 = new javax.swing.JTextField();
        field3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        solBankLabel.setFont(new java.awt.Font("Lucida Grande", 1, 17)); // NOI18N
        solBankLabel.setForeground(new java.awt.Color(255, 255, 255));
        solBankLabel.setText("jLabel4");
        getContentPane().add(solBankLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        solUserLabel.setFont(new java.awt.Font("Lucida Grande", 1, 17)); // NOI18N
        solUserLabel.setForeground(new java.awt.Color(255, 255, 255));
        solUserLabel.setText("jLabel3");
        getContentPane().add(solUserLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        gizliPass.setText("jLabel3");
        getContentPane().add(gizliPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 22, -1, -1));

        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, -1, -1));

        tfBet.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        tfBet.setText("100");
        tfBet.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 3, 18))); // NOI18N
        getContentPane().add(tfBet, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 83, -1));

        btnBet.setText("PLAY");
        btnBet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBetActionPerformed(evt);
            }
        });
        getContentPane().add(btnBet, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 80, 40));

        wonLostLabel.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        wonLostLabel.setText("jLabel3");
        getContentPane().add(wonLostLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 140, 20));

        field1.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        field1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 3, 18))); // NOI18N
        getContentPane().add(field1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 80, -1));

        field2.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        field2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 3, 18))); // NOI18N
        getContentPane().add(field2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 80, -1));

        field3.setFont(new java.awt.Font("Lucida Grande", 3, 18)); // NOI18N
        field3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Lucida Grande", 3, 18))); // NOI18N
        getContentPane().add(field3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkg06royalpavyon/slotresim.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        //Games g = new Games(solUserLabel.getText(), gizliPass.getText(), Double.parseDouble(solBankLabel.getText()));
        for (int i = 0; i < CasinoSys.casinoList.size(); i++) {
            if (solUserLabel.getText().equalsIgnoreCase(CasinoSys.casinoList.get(i).getUsername())) {
                CasinoSys.casinoList.get(i).setBankAccount(Double.parseDouble(solBankLabel.getText()));
            }
        }

        games.setVisible(true);
        this.setVisible(false);
        games.getBankLabel().setText(solBankLabel.getText());
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnBetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBetActionPerformed
        double bet = Double.parseDouble(tfBet.getText());

        ArrayList<Integer> arr = CasinoSys.koluCek();

        int slot1 = arr.get(0);
        int slot2 = arr.get(1);
        int slot3 = arr.get(2);
        field1.setText(""+slot1);
        field2.setText(""+slot2);
        field3.setText(""+slot3);

        if (slot1 == slot2 && slot1 == slot3) {
            wonLostLabel.setText("YOU WON");
            double bank = Double.parseDouble(solBankLabel.getText());
            double bet2 = Double.parseDouble(tfBet.getText());
            double newbank = (bank + bet2);
            solBankLabel.setText("" + newbank);
        } else if (slot1 == slot2 && slot1 != slot3) {
            wonLostLabel.setText("Push.");
        } else if (slot1 == slot3 && slot1 != slot2) {
            wonLostLabel.setText("Push.");
        } else if (slot2 == slot3 && slot2 != slot1) {
            wonLostLabel.setText("Push.");
        } else {
            wonLostLabel.setText("You Lost.");
            double bank = Double.parseDouble(solBankLabel.getText());
            double bet2 = Double.parseDouble(tfBet.getText());
            double newbank = (bank - bet2);
            solBankLabel.setText("" + newbank);
        }
    }//GEN-LAST:event_btnBetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBet;
    private javax.swing.JButton btnClose;
    private javax.swing.JTextField field1;
    private javax.swing.JTextField field2;
    private javax.swing.JTextField field3;
    private javax.swing.JLabel gizliPass;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel solBankLabel;
    private javax.swing.JLabel solUserLabel;
    private javax.swing.JTextField tfBet;
    private javax.swing.JLabel wonLostLabel;
    // End of variables declaration//GEN-END:variables
}
